networks:
  graduation-thesis:
    external: true

services:
  # Cấu hình Spark containers
  spark-master:
    image: spark-monitor
    container_name: spark-master
    hostname: spark-master
    networks:
      - graduation-thesis
    ports:
      - '8080:8080'
      - '7077:7077'
      - '4040:4040'
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_DAEMON_MEMORY=1G
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - spark_master:/bitnami
      - ./Spark/consumer.py:/opt/bitnami/spark/consumer.py
      - ./Spark/dev/consumer.py:/opt/bitnami/spark/consumer_dev.py
      - ./Spark/trend_analysis.py:/opt/bitnami/spark/trend_analysis.py
    restart: always

  spark-worker-1:
    image: spark-monitor
    container_name: spark-worker-1
    hostname: spark-worker-1
    networks:
      - graduation-thesis
    depends_on:
      - spark-master
    ports:
      - '18080:8080'
      - '7078:7077'
      - '4041:4040'
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - spark_worker_1:/bitnami
      - ./Spark/consumer.py:/opt/bitnami/spark/consumer.py
      - ./Spark/dev/consumer.py:/opt/bitnami/spark/consumer_dev.py
      - ./Spark/trend_analysis.py:/opt/bitnami/spark/trend_analysis.py
    deploy:
      resources:
        limits:
          memory: 1024M
    restart: always

  spark-worker-2:
    image: spark-monitor
    container_name: spark-worker-2
    hostname: spark-worker-2
    networks:
      - graduation-thesis
    depends_on:
      - spark-master
      - spark-worker-1
    ports:
      - '28080:8080'
      - '7079:7077'
      - '4042:4040'
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - spark_worker_2:/bitnami
      - ./Spark/consumer.py:/opt/bitnami/spark/consumer.py
      - ./Spark/dev/consumer.py:/opt/bitnami/spark/consumer_dev.py
      - ./Spark/trend_analysis.py:/opt/bitnami/spark/trend_analysis.py
    deploy:
      resources:
        limits:
          memory: 1024M
    restart: always

  spark-worker-3:
    image: spark-monitor
    container_name: spark-worker-3
    hostname: spark-worker-3
    networks:
      - graduation-thesis
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
    ports:
      - '38080:8080'
      - '7080:7077'
      - '4043:4040'
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - spark_worker_3:/bitnami
      - ./Spark/consumer.py:/opt/bitnami/spark/consumer.py
      - ./Spark/dev/consumer.py:/opt/bitnami/spark/consumer_dev.py
      - ./Spark/trend_analysis.py:/opt/bitnami/spark/trend_analysis.py
    deploy:
      resources:
        limits:
          memory: 1024M
    restart: always

  # Cấu hình MySQL container
  mysql:
    image: mysql:8.0.36
    container_name: mysql
    networks:
      - graduation-thesis
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --max_allowed_packet=268425456
    environment:
      - MYSQL_DATABASE=vietnam_stock
      - MYSQL_ROOT_PASSWORD=root

  # Cấu hình cụm Cassandra
  cassandra-1:
    image: cassandra-monitor
    container_name: cassandra-1
    hostname: cassandra-1
    networks:
      - graduation-thesis
    ports:
      - '9042:9042'
      - '7070:7070'
    volumes:
      - cassandra_1:/var/lib/cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra-1,cassandra-2,cassandra-3
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RACK1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - HEAP_NEWSIZE=32M
      - MAX_HEAP_SIZE=512M
      - CLIENT_TIMEOUT=20
    restart: always

  cassandra-2:
    image: cassandra-monitor
    container_name: cassandra-2
    hostname: cassandra-2
    networks:
      - graduation-thesis
    depends_on:
      - cassandra-1
    ports:
      - '9043:9042'
      - '7071:7070'
    volumes:
      - cassandra_2:/var/lib/cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra-1,cassandra-2,cassandra-3
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RACK1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - HEAP_NEWSIZE=32M
      - MAX_HEAP_SIZE=512M
      - CLIENT_TIMEOUT=20
    restart: always

  cassandra-3:
    image: cassandra-monitor
    container_name: cassandra-3
    hostname: cassandra-3
    networks:
      - graduation-thesis
    depends_on:
      - cassandra-1
      - cassandra-2
    ports:
      - '9044:9042'
      - '7072:7070'
    volumes:
      - cassandra_3:/var/lib/cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra-1,cassandra-2,cassandra-3
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_DC=DC2
      - CASSANDRA_RACK=RACK1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - HEAP_NEWSIZE=32M
      - MAX_HEAP_SIZE=512M
      - CLIENT_TIMEOUT=20
    restart: always

  # Cấu hình Grafana container
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - graduation-thesis
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_LOG_LEVEL=debug
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_DEFAULT_APP_MODE=development
    restart: always
    
volumes:
  spark_master:
  spark_worker_1:
  spark_worker_2:
  spark_worker_3:
  mysql_data:
  cassandra_1:
  cassandra_2:
  cassandra_3:
  grafana_data: