global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    monitor: 'Performance monitor'

scrape_configs:
  - job_name: 'graphite-exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:9108']
    metrics_path: '/metrics'