global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    monitor: 'Performance monitor'

scrape_configs:
  # - job_name: 'graphite-exporter'
  #   scrape_interval: 10s
  #   static_configs:
  #     - targets: ['host.docker.internal:9108']
  #   metrics_path: '/metrics'

  - job_name: 'prometheus'
    scrape_interval: 10s
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['localhost:9090'] 
    metrics_path: '/metrics'

  - job_name: 'node-exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'spark-master'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/metrics/master/prometheus'

  - job_name: 'spark-applications'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/metrics/applications/prometheus'
  
  - job_name: 'spark-worker-1'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:18080']
    metrics_path: '/metrics/prometheus'

  - job_name: 'spark-worker-2'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:28080']
    metrics_path: '/metrics/prometheus'
  
  - job_name: 'spark-driver'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:4040']
    metrics_path: '/metrics/executors/prometheus'